Repository lllyasviel/Fooocus, pull requests merged in 2024-02, with the labels that each got.

#2217 Fix broken links
  ldm_patched/contrib/external_canny.py
  ldm_patched/pfn/architecture/HAT.py
  ldm_patched/pfn/architecture/RRDB.py
Labels: Size S

#2195 delay importing of modules.config
  launch.py
Labels: Size S

#2187 Fixed mistakes in HTML generation
  modules/private_logger.py
Labels: Size S

#1905 chore: remove unnecessary comments
  javascript/contextMenus.js
Labels: Size S

#1784 fix: correctly sort files, display deepest dir level first
  modules/util.py
Labels: Size S

#1122 chore: replace custom lcm function with math.lcm
  ldm_patched/modules/conds.py
Labels: question, Size S

#2313 Ignore DS_Store
  .gitignore
Labels: Size S

#1013 add advanced parameter for disable_intermediate_results (progress_gallery)
  language/en.json
  modules/async_worker.py
  webui.py
Labels: Size S

#1256 Add ability to load checkpoints and loras from multiple locations
  launch.py
  modules/config.py
  modules/core.py
  modules/default_pipeline.py
  modules/util.py
Labels: Size M

#1601 Allow users specify number of threads when running on CPU via the extension to --always-cpu arg
  ldm_patched/modules/args_parser.py
  ldm_patched/modules/model_management.py
  readme.md
Labels: Size M

#1631 improve bug report and feature request issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: Size S

#1668 correctly create directory for path_outputs if not existing
  modules/config.py
  modules/util.py
Labels: Size M

#2332 fix: allow path_outputs to be outside of root dir
  webui.py
Labels: Size S

#2210 feat: add button to enable LoRAs
  modules/async_worker.py
  modules/html.py
  modules/meta_parser.py
  webui.py
Labels: Size M

#2215 Add max loras editable config
  modules/async_worker.py
  modules/config.py
  modules/meta_parser.py
  webui.py
Labels: Size M

#1503 Add Array Support on main prompt
  language/en.json
  modules/async_worker.py
  modules/sdxl_styles.py
  webui.py
Labels: Size M

#1932 feat: use consistent file name in gradio
  args_manager.py
  ldm_patched/modules/args_parser.py
  modules/async_worker.py
  modules/private_logger.py
  webui.py
Labels: Size M

#1940 feat: add metadata to images
  args_manager.py
  language/en.json
  modules/async_worker.py
  modules/config.py
  modules/flags.py
  modules/meta_parser.py
  modules/private_logger.py
  modules/util.py
  webui.py
Labels: Size L

#2368 Typo fix
  readme.md
Labels: documentation, Size S
