Repository lllyasviel/Fooocus, pull requests merged in 2024-05, with the labels that each got.

#2855 feat: choose random style
  language/en.json
  modules/async_worker.py
  modules/sdxl_styles.py
  sdxl_styles/samples/random_style.jpg
Labels: Size S

#2454 feat: update anime from animaPencilXL_v100 to animaPencilXL_v310
  presets/anime.json
Labels: Size S

#1920 Full prompt log
  modules/async_worker.py
  modules/private_logger.py
Labels: Size S

#2740 fix: do not close meta tag in HTML header
  modules/ui_gradio_extensions.py
Labels: Size S

#1938 feat: automatically describe image on uov image upload
  args_manager.py
  webui.py
Labels: Size S

#958 add nsfw image censoring via config and checkbox
  extras/censor.py
  extras/safety_checker/configs/config.json
  extras/safety_checker/configs/preprocessor_config.json
  extras/safety_checker/models/safety_checker.py
  language/en.json
  models/safety_checker/put_safety_checker_models_here
  modules/async_worker.py
  modules/config.py
  webui.py
Labels: Size L

#2905 feat: add align your steps scheduler
  ldm_patched/contrib/external_align_your_steps.py
  modules/flags.py
  modules/sample_hijack.py
Labels: Size S

#2323 Adding support to inline prompt references
  development.md
  modules/__init__.py
  modules/async_worker.py
  modules/config.py
  modules/extra_utils.py
  modules/sdxl_styles.py
  modules/util.py
  tests/__init__.py
  tests/test_utils.py
Labels: Size M

#2907 feat: add tcd sampler
  ldm_patched/contrib/external_custom_sampler.py
  ldm_patched/contrib/external_model_advanced.py
  ldm_patched/k_diffusion/sampling.py
  ldm_patched/modules/model_sampling.py
  ldm_patched/modules/samplers.py
  modules/async_worker.py
  modules/flags.py
  modules/patch_precision.py
Labels: Size M

#2812 feat: add performance hyper-sd based on 4step LoRA
  modules/async_worker.py
  modules/config.py
  modules/flags.py
Labels: Size S

#2971 feature: Reads the size and ratio of the image and gives the recommended size
  modules/config.py
  modules/flags.py
  modules/meta_parser.py
  modules/util.py
  webui.py
Labels: Size S

#2805 feat: build and push container image for ghcr.io, update docker.md, and other related fixes
  .dockerignore
  .github/dependabot.yml
  .github/workflows/build_container.yml
  Dockerfile
  docker-compose.yml
  docker.md
  requirements_docker.txt
Labels: documentation, Size M

#2590 Slightly more compact ui settings
  css/style.css
  webui.py
Labels: Size S
