Repository lllyasviel/Fooocus, pull requests merged in 2024-03, with the labels that each got.

#2411 fix: adjust parameters for upscale fast 2x
  modules/async_worker.py
Labels: bug

#2414 fix: add handling for filepaths to image grid
  modules/async_worker.py
Labels: bug

#2430 fix: add fallback value for default_max_lora_number when default_loras is empty
  modules/config.py
Labels: Size S

#2425 feat: add metadata hint to history log
  modules/async_worker.py
  modules/private_logger.py
Labels: Size S

#2431 feat: adjust width of lora weight for firefox
  modules/html.py
  webui.py
Labels: Size S

#2438 feat: match anything in array syntax, not only words and whitespace
  modules/sdxl_styles.py
Labels: Size S

#2453 feat: use jpeg instead of jpg, use enums instead of strings
  modules/config.py
  modules/flags.py
  modules/meta_parser.py
  modules/private_logger.py
  webui.py
Labels: Size S

#2415 feat: add performance sdxl lightning
  modules/async_worker.py
  modules/config.py
  modules/flags.py
  presets/lightning.json
  webui.py
Labels: Size M

#1992 Feat: Add ability to change the Gradio temp path for saving images. Added ability to clear Gradio temp files and folders on launch
  args_manager.py
  launch.py
  modules/config.py
  modules/launch_util.py
  modules/private_logger.py
Labels: Size M

#2466 feat: Scan wildcard subdirectories
  modules/config.py
  modules/sdxl_styles.py
  modules/util.py
  webui.py
Labels: Size S

#2506 fix: use correct method call for interrupt_current_processing
  modules/async_worker.py
Labels: Size S

#1761 Wildcard enhancement, toggle read in order, prompt queue. 通配符增强，切换顺序读取。
  language/en.json
  modules/async_worker.py
  modules/sdxl_styles.py
  webui.py
Labels: Size M

#1883 Styles Grouping/Sorting #1770
  css/style.css
  javascript/script.js
  webui.py
Labels: Size M

#2507 feat: allow to add disabled LoRAs in config
  modules/config.py
  modules/core.py
  presets/anime.json
  presets/default.json
  presets/lcm.json
  presets/realistic.json
  presets/sai.json
  webui.py
Labels: Size M

#2517 fix: update incompatible xformers version
  launch.py
Labels: Size S, package change

#2520 feat: allow user add custom preset without block `git pull`
  presets/.gitignore
Labels: Size S

#1570 Add preset selection to Gradio UI (session based)
  args_manager.py
  language/en.json
  launch.py
  modules/config.py
  modules/meta_parser.py
  presets/realistic.json
  webui.py
Labels: Size M

#2492 Improved Negative Prompt Support for Anime, Paintings and Other Non-Photographic Media #2481
  presets/anime.json
  sdxl_styles/samples/fooocus_semi_realistic.jpg
  sdxl_styles/sdxl_styles_fooocus.json
Labels: Size S

#2571 fix: remove positive prompt from anime prefix
  presets/anime.json
Labels: enhancement
